name: check

on: pull_request

jobs:
  check:
    if: startsWith(github.head_ref, 'dependabot/') == false  # ignore the pull request which comes from user dependabot.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install packages
        run: yarn install
      - name: Linter
        run: yarn lint
